### ISSUE TITLE
Ability to pass `--force` to GHCup

### ISSUE THREAD

**Issue by minoki** [haskell-actions/setup#103]
I want to use LLVM backend on GitHub Actions, so trying to install GHC with `OPT` and `LLC` set:

```yaml
      # GHC <= 9.8 needs LLVM 12: https://gitlab.haskell.org/ghc/ghc/-/issues/23870
      - name: Install LLVM 12 with Homebrew
        run: |
          brew install llvm@12
          echo "OPT=$(brew --prefix llvm@12)/bin/opt" >> "${GITHUB_ENV}"
          echo "LLC=$(brew --prefix llvm@12)/bin/llc" >> "${GITHUB_ENV}"
        if: ${{ (matrix.os == 'macos-13' || matrix.os == 'macos-14') && (matrix.ghc == '9.6' || matrix.ghc == '9.8') }}

      - name: Install LLVM 12 with APT
        run: |
          sudo apt-get install llvm-12 clang-12
          echo "OPT=opt-12" >> "${GITHUB_ENV}"
          echo "LLC=llc-12" >> "${GITHUB_ENV}"
          echo "LLVMAS=clang-12" >> "${GITHUB_ENV}"
        if: ${{ matrix.os == 'ubuntu-22.04' && (matrix.ghc == '9.6' || matrix.ghc == '9.8') }}

      - name: Install LLVM 15 with Homebrew
        run: |
          brew install llvm@15
          echo "OPT=$(brew --prefix llvm@15)/bin/opt" >> "${GITHUB_ENV}"
          echo "LLC=$(brew --prefix llvm@15)/bin/llc" >> "${GITHUB_ENV}"
        if: ${{ (matrix.os == 'macos-13' || matrix.os == 'macos-14') && (matrix.ghc == '9.10' || matrix.ghc == '9.12') }}

      - name: Install LLVM 15 with APT
        run: |
          sudo apt-get install llvm-15 clang-15
          echo "OPT=opt-15" >> "${GITHUB_ENV}"
          echo "LLC=llc-15" >> "${GITHUB_ENV}"
          echo "LLVMAS=clang-15" >> "${GITHUB_ENV}"
        if: ${{ matrix.os == 'ubuntu-24.04' && (matrix.ghc == '9.10' || matrix.ghc == '9.12') }}

      - uses: haskell-actions/setup@v2
        name: Setup Haskell
        with:
          ghc-version: ${{ matrix.ghc }}
```

...but this does not seem to work if GHC is already installed in the runner image. Passing `--force` to GHCup may improve the situation.

Is there a way to pass `--force` to GHCup?
