### ISSUE TITLE
Caching cabal-store on windows seems to fail

### ISSUE THREAD

**Issue by robinheghan** [haskell-actions/setup#106]
I've currently setup my github actions workflow to cache the cabal store like this

```yaml
      - name: Cache cabal store
        uses: actions/cache@v4
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: deps-win-${{ env.ghc }}-${{ hashFiles('cabal.project.freeze') }}
```

When executed, it looks like this:

<img width="1169" alt="Skjermbilde 2025-01-04 kl  07 59 20" src="https://github.com/user-attachments/assets/2c2592d4-731e-4b5b-a54b-25face1892c6" />

It seems to cache _something_, but when building my project on a windows runner it still redownloads and builds all dependencies. Am I doing something wrong?

The same setup works on mac runners.

BTW: how can I cache the ghc/cabal installs on Windows? The majority of time spent in my Windows runner is installing ghc and cabal.
