### ISSUE TITLE
Document how to cache stack

### ISSUE THREAD

**Issue by philderbeast** [haskell-actions/setup#86]
How should we set up this action to cache stack, like [cabal with caching](https://github.com/haskell-actions/setup#model-cabal-workflow-with-caching). Here's the [caching for liquid-fixpoint](https://github.com/ucsd-progsys/liquid-fixpoint/blob/50d3a7e5fd9e00be1d334378bacf24736d7f6c3c/.github/workflows/stack.yml#L45C1-L51):

```yaml
      - name: Cache ~/.stack and .stack-work
        uses: actions/cache@v3
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack-${{ hashFiles('**/*.cabal', './stack.yaml', './stack.yaml.lock') }}
  ```
