### ISSUE TITLE
Is it possible to install two GHC versions (and two Cabal versions)?

### ISSUE THREAD

**Issue by philderbeast** [haskell-actions/setup#87]
Is it possible to install two GHC versions (and two Cabal versions[^1])? I encountered a situation where I want to build a project with `ghc-9.8.2` and `cabal-install-3.10.3.0` but to get there I need to first run a Stack script that needs other versions installed. Stack will do that for me but it takes a long time, about 10 mins on Github's runners.

```Haskell
#!/usr/bin/env stack
-- stack script --resolver=lts-18.27 --package=base --package=dhall --package=filepath --package=text
```

> Stackage snapshot LTS 18.27 specifies GHC 8.10.7. GHC 8.10.7's Cabal boot library is Cabal-3.2.1.0.
From https://github.com/commercialhaskell/stack/issues/6588#issuecomment-2121204982

[^1]: I'm not sure exactly what Stack needs to get going here, perhaps it is just `ghc-8.10.7` with included Cabal boot library?

**Comment by andreasabel** [comment]
Did you try to run the action twice?  The action does not uninstall GHC or cabal, afaik, so maybe this just works?
Of course, different versions of cabal are not entirely compatible, and they use the same store, so this could cause problem.  (E.g. alternating between cabal version will cause it to rebuild the index cache at each switch.)

**Comment by philderbeast** [comment]
> Did you try to run the action twice? The action does not uninstall GHC or cabal, afaik, so maybe this just works?

Yes it looks like installing twice works, as can be seen in [this trial run](https://github.com/cabalism/hpack-dhall/actions/runs/9197644024/job/25298572646) where I install `ghc-8.10.7` for the scripts of Updo and other versions of GHC for building the project I'm testing. Stack itself is not happy with this set up and takes ages to compile `.stack/setup-exe-src/setup-shim-HwdwpEmb.hs`.

**Comment by philderbeast** [comment]
Here's a simpler workflow and its [output](https://github.com/cabalism/hpack-dhall/actions/runs/9206539082/job/25324599251) that shows it is possible to install two versions of GHC.

```yaml
name: stack

on:
  push:
    branches: [main, ci/check-versions]
  pull_request:
    branches: [main]

jobs:
  build:
    name: ghc-${{ matrix.vers.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.10.3.0"]
        vers:
          - {ghc: "9.8.2", stackage: "nightly-2024-05-18"}

    steps:
    - uses: actions/checkout@v4

    - name: Set up GHC and cabal-install from matrix
      uses: haskell-actions/setup@v2
      id: setup
      with:
        ghc-version: ${{ matrix.vers.ghc }}
        cabal-version: ${{ matrix.cabal }}
        enable-stack: true
        stack-version: '2.15.7'

    - name: Set up GHC 8.10.7 by itself
      uses: haskell-actions/setup@v2
      with:
        ghc-version: "8.10.7"

    - name: Check installation
      run: |
        ghc --version
        ghc-9.8.2 --version
        ghc-8.10.7 --version
        cabal --version
        stack --version     
```
